name: 'Terraform Apply on Merge'

on:
  pull_request:
    # types: [closed]
    branches:
      - main

# Use a concurrency group to ensure serialized execution
concurrency: 
    group: terraform-apply-main
    cancel-in-progress: false

jobs:
  terraform-apply:
    if: ${{ github.event.pull_request.merged == true }}
    name: 'Terraform Apply'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.6

      - uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}' # Replace with the name of your GitHub Actions secret

      - name: Terraform Init
        id: terraform-init
        run: terraform init

      - name: Terraform Validate
        id: terraform-validate
        run: terraform validate -no-color

      - name: Terraform Apply
        id: terraform-apply
        run: terraform apply -auto-approve
